# Generated by Django 3.2.5 on 2021-08-04 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0010_auto_20210801_1623'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0012_auto_20210802_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت کننده')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.organization', verbose_name='سازمان')),
            ],
            options={
                'verbose_name': 'پیش فاکتور',
                'verbose_name_plural': 'پیش فاکتورها',
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.PositiveSmallIntegerField(verbose_name='درصد تخفیف')),
                ('number', models.PositiveIntegerField(verbose_name='تعداد ')),
                ('base_cost', models.PositiveIntegerField(verbose_name='قیمت خام')),
                ('cost_with_taxation', models.PositiveIntegerField(default=0, verbose_name='قیمت با مالیات')),
                ('final_cost_with_discount', models.PositiveIntegerField(default=0, verbose_name='قیمت نهایی با تخفیف')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='انتخاب دستگاه از لیست')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.quote')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('content', models.TextField(default=None, max_length=400, verbose_name='متن پیگیری')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت کننده')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization', verbose_name='سازمان')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteEmailHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.EmailField(max_length=254, verbose_name='ایمیل گیرنده')),
                ('was_successfull', models.BooleanField(default=False, verbose_name='ایمیل ارسال شد؟')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('user_sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر ارسال کننده')),
            ],
        ),
    ]
