# Generated by Django 3.2.5 on 2021-08-05 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_auto_20210805_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteitem',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.quote', verbose_name='محصول'),
        ),
    ]
