# Generated by Django 3.2.5 on 2021-08-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0003_alter_quoteitem_quote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quoteitem',
            old_name='cost_with_taxation',
            new_name='cost_with_tax',
        ),
        migrations.RemoveField(
            model_name='quoteitem',
            name='base_cost',
        ),
        migrations.RemoveField(
            model_name='quoteitem',
            name='final_cost_with_discount',
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='final_price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت نهایی'),
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت '),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='number',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد '),
        ),
    ]
