# Generated by Django 3.2.5 on 2021-08-05 17:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20210805_1659'),
        ('quote', '0006_auto_20210805_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quoteitem',
            options={'verbose_name': 'رکورد پیش فاکتور', 'verbose_name_plural': 'رکورد پیش فاکتورها'},
        ),
        migrations.RemoveField(
            model_name='quoteitem',
            name='cost_with_tax',
        ),
        migrations.RemoveField(
            model_name='quoteitem',
            name='final_price',
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='discount',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف'),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='number',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.quote', verbose_name='پیش فاکتور'),
        ),
    ]
