# Generated by Django 3.2.5 on 2021-08-11 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0007_auto_20210805_1733'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuoteFollowUp',
        ),
    ]
