# Generated by Django 3.2.5 on 2021-07-29 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20210729_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationmachin',
            name='products',
        ),
    ]
