# Generated by Django 3.2.5 on 2021-07-30 07:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0008_remove_product_machine'),
        ('organization', '0003_remove_organizationmachin_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_name', models.CharField(max_length=20, verbose_name='استان')),
                ('organization_name', models.CharField(max_length=50, verbose_name='نام سازمان')),
                ('organization_phone', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='تلفن شما معتبر نمی باشد', regex='^((?:\\+98|0)(\\d){2}(\\d){8})$')], verbose_name='شماره تلفن سازمان')),
                ('organization_staff', models.PositiveIntegerField(verbose_name='تعداد کارگران')),
                ('personnel_name', models.CharField(max_length=50, verbose_name='نام و نام خانوادگی کارفرما')),
                ('personnel_mobile', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='موبایل شما معتبر نمی باشد', regex='(\\+98|0)?9\\d{9})')], verbose_name='موبایل کارفرما')),
                ('personnel_email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.RegexValidator(message='ایمیل شما معتبر نیست', regex='/^\\w+([\\.-]?\\w+)*@\\w+([\\.-]?\\w+)*(\\.\\w{1,3})$/')], verbose_name='ایمیل کارفرما')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('expert_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت کننده')),
                ('manufacturedـproduct', models.ManyToManyField(to='product.Product', verbose_name='محصولات تولیدی')),
            ],
        ),
        migrations.DeleteModel(
            name='OrganizationMachin',
        ),
    ]
