# Generated by Django 3.2.5 on 2021-07-30 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20210730_0732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'سازمان', 'verbose_name_plural': 'سازمانها'},
        ),
    ]
