# Generated by Django 3.2.5 on 2021-07-30 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_alter_organization_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='expert_creator',
            new_name='creator',
        ),
    ]
