# Generated by Django 3.2.5 on 2021-07-30 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_rename_expert_creator_organization_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='manufacturedـproduct',
            new_name='manufactured_product',
        ),
    ]
