# Generated by Django 3.2.5 on 2021-07-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_rename_manufacturedـproduct_organization_manufactured_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='محصولات تولیدی کارفرما')),
            ],
            options={
                'verbose_name': 'محصول تولیدی',
                'verbose_name_plural': 'محصولات تولیدی',
            },
        ),
        migrations.AlterField(
            model_name='organization',
            name='manufactured_product',
            field=models.ManyToManyField(to='organization.OrganizationProduct', verbose_name='محصولات تولیدی'),
        ),
    ]
