# Generated by Django 3.2.5 on 2021-08-01 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_auto_20210730_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_phone',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='تلفن شما معتبر نمی باشد', regex='^((?:\\+98|0)(\\d){2}(\\d){8})$')], verbose_name='شماره تلفن سازمان'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='personnel_email',
            field=models.EmailField(blank=True, max_length=254, validators=[django.core.validators.RegexValidator(message='ایمیل شما معتبر نیست', regex='/^\\w+([\\.-]?\\w+)*@\\w+([\\.-]?\\w+)*(\\.\\w{1,3})$/')], verbose_name='ایمیل کارفرما'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='personnel_mobile',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='موبایل شما معتبر نمی باشد', regex='(\\+98|0)?9\\d{9})')], verbose_name='موبایل کارفرما'),
        ),
    ]
