# Generated by Django 3.2.5 on 2021-08-05 14:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0010_auto_20210801_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='استان')),
            ],
            options={
                'verbose_name': 'استان',
                'verbose_name_plural': 'استان ها',
            },
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='manufactured_product',
            new_name='organization_product',
        ),
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together={('organization_name', 'creator')},
        ),
    ]
