# Generated by Django 3.2.5 on 2021-08-06 05:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_auto_20210805_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='personnel_mobile',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='موبایل شما معتبر نمی باشد', regex='((\\+98|0)?9\\d{9})')], verbose_name='موبایل کارفرما'),
        ),
    ]
