# Generated by Django 3.2.5 on 2021-07-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_category', '0005_remove_productcategory_product'),
        ('product', '0006_auto_20210729_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='product_category.ProductCategory', verbose_name='دسته بندی ها'),
        ),
    ]
