# Generated by Django 3.2.5 on 2021-08-02 08:04

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_auto_20210801_1623'),
        ('product', '0010_auto_20210801_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='organizationproduct',
        ),
        migrations.AddField(
            model_name='product',
            name='catalogue_image',
            field=models.ImageField(blank=True, null=True, upload_to=product.models.upload_image_path, verbose_name='عکس کاتالوگ(jpeg)'),
        ),
        migrations.AddField(
            model_name='product',
            name='catalogue_pdf',
            field=models.FileField(blank=True, null=True, upload_to=product.models.upload_pdf_path, verbose_name='فایل کاتالوگ(PDF)'),
        ),
        migrations.AddField(
            model_name='product',
            name='organization_product',
            field=models.ManyToManyField(blank=True, to='organization.OrganizationProduct', verbose_name='قابل استفاده برای تولید محصولات تولیدی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='ویژگی های فنی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax',
            field=models.BooleanField(default=False, verbose_name='مشمول مالیات'),
        ),
    ]