# Generated by Django 3.2.5 on 2021-08-02 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20210802_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catalogue_image',
            new_name='file_image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='catalogue_pdf',
            new_name='file_pdf',
        ),
    ]
