# Generated by Django 3.2.5 on 2021-08-05 16:59

import django.core.validators
from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20210802_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=150, null=True, verbose_name='اسم محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='file_image',
            field=models.ImageField(blank=True, upload_to=product.models.upload_image_path, verbose_name='تصویر محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='file_pdf',
            field=models.FileField(blank=True, upload_to=product.models.upload_pdf_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='کاتولوگ محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(verbose_name='قیمت'),
        ),
    ]
