# Generated by Django 3.2.5 on 2021-08-06 05:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20210805_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file_image',
            field=models.ImageField(blank=True, upload_to='Product/Images', verbose_name='تصویر محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='file_pdf',
            field=models.FileField(blank=True, upload_to='Product/PDFs', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='کاتولوگ محصول'),
        ),
    ]
