# Generated by Django 3.2.5 on 2021-07-28 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_accounts',
        ),
    ]
