# Generated by Django 3.2.5 on 2021-07-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210729_1209'),
        ('product_category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='product',
            field=models.ManyToManyField(blank=True, to='product.Product', verbose_name='محصولات'),
        ),
    ]
